// Increment if encoding layout, descriptor IDs, or value types change. Previous Concordance versions will not be able
// to decode buffers generated by a newer version, so changing this value will require a major version bump of
// Concordance itself. The version is encoded as a CBOR integer.
//
// Note that previous versions encoded the version as an unsigned 16 bit integer. This ended with version 3, which would
// have been encoded as `03 00`. This means older versions will still recognize the CBOR integer values as being larger
// and therefore incompatible. Additionally, this version will recognize older version numbers as being smaller.
export const version = 4

// Note that the type indexes are encoded as CBOR integers. 0–23 can be stored in a single byte, while 24–255 require
// two bytes. Reserve the first 24 indexes for the most common types, and use the remaining indexes for less common
// types.

export const staticTypeTable = {
  terminator: 0 as const, // Designates that the previous value is the last in a sequence. Not used when encoding primitives, externals or pointers.
  pointer: 1 as const, // Designates values that are used more than once.
  bigint: 2 as const, // Primitives.
  boolean: 3 as const,
  null: 4 as const,
  number: 5 as const,
  string: 6 as const,
  symbol: 7 as const,
  undefined: 8 as const,
  object: 9 as const, // Objects.
  array: 10 as const,
  map: 11 as const,
  set: 12 as const,
  arrayBufferView: 13 as const,
  date: 14 as const,
  regExp: 15 as const,
  error: 16 as const,
  // 17-23 reserved for future use

  elementAspect: 24 as const, // The following values (up to the next aspect or terminator) are interpreted as array(like) elements.
  iteratorValueAspect: 25 as const, // The following values (up to the next aspect or terminator) are interpreted as iterator values.
  mapEntryAspect: 26 as const, // The following values (up to the next aspect or terminator) are interpreted as map entries.
  namedPropertyAspect: 27 as const, // The following values (up to the next aspect or terminator) are interpreted as named properties.
  symbolPropertyAspect: 28 as const, // The following values (up to the next aspect or terminator) are interpreted as symbol properties.
  // 29-31 reserved for future use

  arguments: 32 as const,
  arrayBuffer: 33 as const,
  boxedPrimitive: 34 as const,
  cryptoKey: 35 as const,
  external: 36 as const,
  function: 37 as const,
  moduleNamespaceObject: 38 as const,
  promise: 39 as const,
  weakMap: 40 as const,
  weakSet: 41 as const,
}

export type StaticType = (typeof staticTypeTable)[keyof typeof staticTypeTable]

const validStaticTypes = new Set<number>(Object.values(staticTypeTable))
export function isValidStaticType(type: number): type is StaticType {
  return validStaticTypes.has(type)
}

export type AspectType =
  | typeof staticTypeTable.elementAspect
  | typeof staticTypeTable.iteratorValueAspect
  | typeof staticTypeTable.mapEntryAspect
  | typeof staticTypeTable.namedPropertyAspect
  | typeof staticTypeTable.symbolPropertyAspect

export function isValidAspectType(type: number): type is AspectType {
  return type >= staticTypeTable.elementAspect && type <= staticTypeTable.symbolPropertyAspect
}
