export { default as cloneDeep } from './cloneDeep.js';
export { default as eq } from './eq.js';
export { default as isArguments } from './isArguments.js';
export { default as isArray } from './isArray.js';
export { default as isArrayLike } from './isArrayLike.js';
export { default as isArrayLikeObject } from './isArrayLikeObject.js';
export { default as isBuffer } from './isBuffer.js';
export { default as isFunction } from './isFunction.js';
export { default as isLength } from './isLength.js';
export { default as isMap } from './isMap.js';
export { default as isObject } from './isObject.js';
export { default as isObjectLike } from './isObjectLike.js';
export { default as isPlainObject } from './isPlainObject.js';
export { default as isSet } from './isSet.js';
export { default as isTypedArray } from './isTypedArray.js';
export { default as toPlainObject } from './toPlainObject.js';
export { default } from './lang.default.js';
